# Generated by Django 2.2 on 2019-04-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('length', models.IntegerField()),
                ('pic', models.ImageField(upload_to='media/images/')),
                ('company', models.CharField(max_length=50)),
            ],
        ),
    ]
