# Generated by Django 2.2 on 2019-04-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_tour_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='pic',
            field=models.ImageField(upload_to='images'),
        ),
    ]
