# Generated by Django 2.2 on 2019-05-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('credit', 'Credit card'), ('debit', 'Debit card'), ('paypal', 'PayPal')], default='credit', max_length=20),
        ),
    ]
