# Generated by Django 2.2 on 2019-04-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guestFirstName',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guestLastName',
        ),
    ]
