# Generated by Django 2.2 on 2019-04-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='CheckIn',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='CheckOut',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='totalPrice',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
