# Generated by Django 2.2 on 2019-04-30 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20190430_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='enddate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='no_of_people',
            new_name='number_of_people',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='startdate',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default='testUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
