# Generated by Django 2.2 on 2019-05-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20190502_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
