# Generated by Django 2.2 on 2019-05-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('poor', 'poor'), ('fair', 'fair'), ('good', 'good'), ('very good', 'very good'), ('excelent', 'excelent')], default='good', max_length=9),
        ),
    ]
