# Generated by Django 2.2 on 2019-05-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20190501_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
