# Generated by Django 2.2 on 2019-05-02 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20190430_1541'),
        ('review', '0006_auto_20190501_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tour',
        ),
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.Booking'),
        ),
    ]
